# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tlfbv676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Elia/Documenti/Codici/progetto_RL/progetto_RL.cache/wt [current_project]
set_property parent.project_path C:/Elia/Documenti/Codici/progetto_RL/progetto_RL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Elia/Documenti/Codici/progetto_RL/progetto_RL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Elia/Documenti/Codici/progetto_RL/progetto_RL.srcs/sources_1/new/progetto_reti_logiche.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Elia/Documenti/Codici/progetto_RL/progetto_RL.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files C:/Elia/Documenti/Codici/progetto_RL/progetto_RL.srcs/constrs_1/new/clock.xdc]


synth_design -top project_reti_logiche -part xc7k160tlfbv676-2L


write_checkpoint -force -noxdef project_reti_logiche.dcp

catch { report_utilization -file project_reti_logiche_utilization_synth.rpt -pb project_reti_logiche_utilization_synth.pb }
